apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image }}
          args: ["start-dev"]
          ports:
            - containerPort: 8080
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN_LOGIN
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: auth-service-db
            - name: KC_DB_URL_DATABASE
              value: {{ .Values.postgres.db }}
            - name: KC_DB_USERNAME
              value: {{ .Values.postgres.user }}
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-server-postgres-secret
                  key: POSTGRES_PASSWORD