apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
stringData:
  KEYCLOAK_ADMIN_LOGIN: "{{ .Values.keycloak.adminUser }}"
  KEYCLOAK_ADMIN_PASSWORD: "{{ .Values.keycloak.adminPassword }}"