pipeline {
    agent any

    parameters {
        choice(name: 'ENV', choices: ['test', 'prod'], description: 'Environment')
    }

    environment {
        svc = 'frontend'
        DOCKER_REPO = 'oleg1997'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Set commit hash') {
            steps {
                script {
                    env.COMMIT_HASH = sh(
                        script: 'git rev-parse --short HEAD',
                        returnStdout: true
                    ).trim()
                }
            }
        }

        stage('Build') {
            steps {
                sh "./gradlew clean build :${svc}"
            }
        }

        stage('Docker build & push') {
            steps {
                script {
                    sh """
                      docker build -t ${DOCKER_REPO}/${svc}:${COMMIT_HASH} ${svc}
                      docker push ${DOCKER_REPO}/${svc}:${COMMIT_HASH}
                    """
                }
            }
        }

        stage('Prod approval') {
            when {
                expression { params.ENV == 'prod' }
            }
            steps {
                input message: 'Deploy to PROD environment?', ok: 'Yes, deploy'
            }
        }

        stage('Deploy') {
            steps {
                sh """
                  helm upgrade --install ${svc} ./bank-chart \
                    --namespace ${params.ENV} \
                    --set image.tag=${COMMIT_HASH}
                """
            }
        }
    }

    post {
        success {
            echo "Deployment to ${params.ENV} successful"
        }
        failure {
            echo "Pipeline failed"
        }
    }
}