{
 "title": "Business errors dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Update balance errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Update Balance errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(error_update_balance_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balance update errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(error_update_balance_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Money transfer errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Money Transfer errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(error_money_transfer_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Money transfer errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(error_money_transfer_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  },
  {
   "title": "Notification errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "sum(error_notification)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Notification errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(error_notification[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}