apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  application.yml: |
    spring:
      security:
        oauth2:
          client:
            registration:
              keycloak:
                client-id: bank-frontend
                client-secret: ${BANK_FRONT_UI_SECRET}
                scope: openid, profile, email
                authorization-grant-type: authorization_code
                redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider:
              keycloak:
                issuer-uri: ${AUTH_SERVER_URL}/realms/bank
    gateway:
      url: ${API_GATEWAY_URL}

    management:
      tracing:
        export:
          zipkin:
            endpoint: {{ .Values.global.zipkin.endpoint }}
        sampling:
          probability: 1
      endpoints:
        web:
          exposure:
            include: health, metrics, prometheus

    logging:
      level:
        com.tarasov.bank: INFO