apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: CONFIG_LOCATION
              value: "optional:file:/config/application.yml"
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
            - name: SPRING_CLOUD_CONSUL_ENABLED
              value: "false"
            - name: AUTH_SERVER_URL
              value: {{ .Values.authServerUrl }}
            - name: ACCOUNT_SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: ACCOUNT_SERVICE_SECRET
            - name: NOTIFICATION_SERVICE_URL
              value: {{ .Values.notificationServiceUrl }}
            - name: ACCOUNT_DB_URL
              value: "jdbc:postgresql://account-service-db:5432/bank"
            - name: ACCOUNT_DB_USERNAME
              value: {{ .Values.postgres.user }}
            - name: ACCOUNT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: account-db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: config
              mountPath: /config
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Chart.Name }}-config