apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  application.yml: |
    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: ${AUTH_SERVER_URL}/realms/bank
          client:
            provider:
              keycloak:
                issuer-uri: ${AUTH_SERVER_URL}/realms/bank
            registration:
              transfer-service:
                provider: keycloak
                authorization-grant-type: client_credentials
                client-id: transfer-service
                client-secret: ${TRANSFER_SERVICE_SECRET}
      kafka:
        bootstrap-servers: bank-chart-kafka-broker-0.bank-chart-kafka-headless:9092,bank-chart-kafka-broker-1.bank-chart-kafka-headless:9092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
          retries: {{ .Values.global.notifications.retry.amount }}
          acks: all
          properties:
            enable.idempotence: true
            retry.backoff.ms: {{ .Values.global.notifications.retry.backoff }}

    account-service:
      url: ${ACCOUNT_SERVICE_URL}

    management:
      tracing:
        export:
          zipkin:
            endpoint: {{ .Values.global.zipkin.endpoint }}
        sampling:
          probability: 1