replicaCount: 2

image:
  repository: oleg1997/bank-api-gateway
  tag: "1.0.3"

authServerUrl: "http://keycloak.default.svc.cluster.local"
accountServiceUrl: "http://account-service:8080"
transferServiceUrl: "http://transfer-service:8080"
cashServiceUrl: "http://cash-service:8080"