replicaCount: 2

hostUrl: "http://localhost:30081"
externalPort: 30081
authServerUrl: "http://keycloak.default.svc.cluster.local"
apiGatewayUrl: "http://api-gateway:8080"
frontendUiAuthSecret: "temp_secret"

image:
  repository: oleg1997/bank-frontend
  tag: "1.0.3"

startupProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health
    port: http
livenessProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health/liveness
    port: http
readinessProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health/readiness
    port: http