replicaCount: 2

image:
  repository: oleg1997/bank-notification-service
  tag: "1.1.0"

authServerUrl: "http://keycloak.default.svc.cluster.local"

startupProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health
    port: http
livenessProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health/liveness
    port: http
readinessProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health/readiness
    port: http