apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  application.yml: |
    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: ${AUTH_SERVER_URL}/realms/bank

    logging:
      level:
        com.tarasov.bank.notification.service: INFO