keycloak:
  image:
    registry: docker.io
    repository: keycloak/keycloak
    tag: 26.5.2
  adminUser: admin
  adminPassword: admin
  adminRealm: bank

frontend-ui:
  replicaCount: 2
  externalPort: 30081
  image:
    tag: "1.0.1"

global:
  security:
    allowInsecureImages: true

kafka:
  broker:
    replicaCount: 2