replicaCount: 2

image:
  repository: oleg1997/bank-cash-service
  tag: "1.0.0"

authServerUrl: "http://keycloak"
accountServiceUrl: "http://account-service"
notificationServiceUrl: "http://notification-service"

startupProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health
    port: http
livenessProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health/liveness
    port: http
readinessProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health/readiness
    port: http