replicaCount: 2

image:
  repository: oleg1997/bank-cash-service
  tag: "1.1.0"

authServerUrl: "http://keycloak.default.svc.cluster.local"
accountServiceUrl: "http://account-service:8080"
notificationServiceUrl: "http://notification-service:8080"
cashServiceAuthSecret: "temp_secret"

startupProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health
    port: http
livenessProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health/liveness
    port: http
readinessProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health/readiness
    port: http